apiVersion: v1
kind: Pod
metadata:
  name: my-pod3
spec:
  schedulerName: PriorityAware
  containers:
    name: my-container
      image: my-image
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  priorityClassName: low-priority